/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AreaSelector: typeof import('./src/components/AreaSelector.vue')['default']
    DocViewer: typeof import('./src/components/DocViewer.vue')['default']
    ExcelViewer: typeof import('./src/components/ExcelViewer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconImage: typeof import('./src/components/IconImage.vue')['default']
    ImageIcon: typeof import('./src/components/ImageIcon.vue')['default']
    MobileTable: typeof import('./src/components/MobileTable.vue')['default']
    MobileTableDemo: typeof import('./src/components/MobileTableDemo.vue')['default']
    MobileTableExample: typeof import('./src/components/MobileTableExample.vue')['default']
    PdfViewer: typeof import('./src/components/PdfViewer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanCascader: typeof import('vant/es')['Cascader']
    VanField: typeof import('vant/es')['Field']
    VanForm: typeof import('vant/es')['Form']
    VanIcon: typeof import('vant/es')['Icon']
    VanList: typeof import('vant/es')['List']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanPopup: typeof import('vant/es')['Popup']
    VanPullRefresh: typeof import('vant/es')['PullRefresh']
    VanSearch: typeof import('vant/es')['Search']
    VanTab: typeof import('vant/es')['Tab']
    VanTabs: typeof import('vant/es')['Tabs']
  }
}
